#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi
 
if [ -f REM_this_is_jail ];
then
    chmod -R u+r .
    chmod -R go-wx+r .
    chmod o-r * .*
    chmod o+r static
    chmod go+x . 
    chmod a+rx bin
    chmod a+rx bin/python3*
    chmod -R go+x lib64
    chmod -R go+x lib
    chmod -R go+x dev
    chmod -R go+x include
    chmod -R go+rx static
    # the next one might not exist
    chmod --silent -R go+x usr

    # change these to your user name
    sudo chown -R cscircles *
    sudo chgrp -R cscircles *

    mkdir -p scratch
    sudo rm -rf scratch/*
    # this allows the webserver to create scratch subdirectories
    sudo chgrp www-data scratch
    chmod g+rwx scratch
    chmod o-rwx scratch
else
   echo "This script must be run in jail" 1>&2
   exit 1
fi
